### PR TITLE
Fixes #95

### LINKED ISSUE #95: bug motion is deprecated use motion.create
**Describe the bug**
Receiving a `motion() is deprecated. Use motion.create() instead.` warning in the console.

**To Reproduce**
1. Start local server.
2. Navigate to http://localhost:5173/ in the browser.
3. Open up `Dev Tools`.
4. Select the `Console` tab.
5. look for warning in the screenshot.

**Expected behavior**
Not to see the warning at all.

**Screenshots**

Image

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - ~Version [e.g. 22]~

**Smartphone (please complete the following information):**

**Additional context**

**To Do**
_**Create an issue and a branch for each of these.**_

- [x] Create a new branch. Use the branch associated with the `Parent Issue` as the `Branch Source`. Checkout the new branch.

- [x] Address issue.

- [ ] Administrative cleanup.

  - [ ] In this https://github.com/users/JamieBort/projects/1/views/4, all `In Progress` Issues with `Rebuild Frontend` milestone assignments should be closed out.

  - [ ] Add significant comments to the code that I added. And to any other code that should have some explanation.
To facilitate this process, compare the code between the current commit and the most recent commit from the parent branch. `git commit -m "Add comments."`

  - [ ] Clean up and organize AI Queries.

  - [ ] Address `Future features` below.

  - [ ] Remove all files that begin with `copy_` in their name. `git commit -m "Remove superfluous files."`

  - [ ] Address all `TODO:` comments. `git commit -m "Address TODO comments."`

  - [ ] Remove all old commented out code. `git commit -m "Remove all old commented out code."`

  - [ ] Verify the app works live on THIS branch. `git commit -m "Push changes to view on live site. Issue #issue_number`.

  - [ ] Push current branch with this comment `git commit -m "Fixes #issue_number"`

  - [ ] Merge this branch into the parent branch.

  - [ ] Verify the app works live on PARENT branch.

  - [ ] Remove all merged branches, backup branches, and the like.

  - [ ] Push to master before proceeding on to the other issues/branches. To make sure nothing broke.

### PR DESCRIPTION
**Pull request by JamieBort**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
I updated lines of code that used `motion()` to use `motion.create()` instead.
## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist

_If your PR includes UI changes, please utilize this checklist:_

- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [x] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

File: frontend/src/components/FloatingChoicePrompt.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ const FloatingPromptWrapperColor = theme.colors.light;
 
 // Using "motion" to style the prompt such that it matches the color of the two language toggles.
 // As a result added the "initial", "animate", and "transition" properties.
-const FloatingPromptWrapper = motion(styled.div`
+const FloatingPromptWrapper = motion.create(styled.div`
```
Comment (JamieBort) [inline frontend/src/components/FloatingChoicePrompt.tsx:20]: Looks good.

File: frontend/src/components/layout/Layout.tsx [hunk 2]
```diff
@@ -23,7 +23,7 @@ const DesktopLanguageWrapperColor = theme.colors.light;
 
 // Using "motion" to style the toggle such that it matches the color of the prompt.
 // As a result added the "initial", "animate", and "transition" properties.
-const DesktopLanguageWrapper = motion(styled.div`
+const DesktopLanguageWrapper = motion.create(styled.div`
```
Comment (JamieBort) [inline frontend/src/components/layout/Layout.tsx:26]: Looks good.

**Review by JamieBort — COMMENTED** [review]
Everything looks good.
